version: '3.10'

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    hostname: redis

  flower:
    build: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app flower
    depends_on:
      - redis
    ports:
      - 5555:5555

  worker:
    build: .
    entrypoint: celery
    command: -A celery_app worker --loglevel=info
    depends_on:
      - redis
